version: '3'
services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXTAUTH_SECRET = "ZyP3Sr9UDSR09IEerCk0t3rdDlorvbnhCW+EClKk51M="
      - NEXTAUTH_URL = "http://localhost:3000/"
      - NEXT_PUBLIC_APIURL = "http://103.131.196.141:8081"
      - NEXT_PUBLIC_APIURL2 = "http://localhost:8081"
