import type { Metadata } from 'next'
import './globals.css'
import { Inter as FontSans } from "next/font/google"
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false
import { GeistSans } from "geist/font/sans";
import { cn } from "../lib/utils"
import Provider from '@/context/Provider';
import { ReduxProvider } from '@/redux/provider';
// import { getServerSession } from 'next-auth';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// const session = getServerSession();
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) 
{
  return (
    <html lang="en">
      <body
        className={GeistSans.className }>
            <ReduxProvider>
          <Provider>
        {children}
          </Provider>
            </ReduxProvider>
      </body>
    </html>
  )
}
